### ISSUE TITLE
[bug]: Clicking on input pins still resets clock on Chrome #320

### ISSUE THREAD

**Issue by Apitheia** [DavidSouther/computron5k#324]
### Program

Hardware Simulator

### Interface

Website (https://nand2tetris.github.io/web-ide)

### What happened?

Note: this works correctly on Firefox.

On Chrome, clicking on an input pin resets other pins and the clock to 0.

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidSouther** [comment]
I have just tested on Chrome using a Bit implementation and the Builtin chip. At no point did toggling the input bit affect the current clock tick or other pins. If you have a video or instructions on how you triggered this bug, or if you feel I have misunderstood the issue, please re-open it and include them in a comment 

https://github.com/nand2tetris/web-ide/assets/498712/17460784-8092-4071-99d7-59460fd9e97e
