### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by K1w1czzz** [DavidSouther/computron5k#497]
### Tool

Hardware Simulator

### Interface

Website (https://nand2tetris.github.io/web-ide)

### Contact Details

scyzc14@nottingham.edu.cn

### What happened?

A bug happened!

### Do you want to try to fix this bug?

- [X] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lyrakisk** [comment]
Hey @K1w1czzz , I think you forgot to update the issue title and fill in the `What happened` section.
