### ISSUE TITLE
HDL Syntax Errors: Display issue

### ISSUE THREAD

**Issue by Shimon-Schocken** [DavidSouther/computron5k#68]
We have to decide where to display the HDL syntax errors stream, IDE UI-wise.  For now, let's display them somewhere, for testing purposes, since we'll worry about the entire IDE UI layout later in the project.  See [this issue](https://github.com/DavidSouther/computron5k/issues/67).

**Comment by DavidSouther** [comment]
Parse errors currently show up in the status line, when `eval` ing chips or `execute`ing tests. I think what would work better is having a list of errors from the current version - it looks like that is the set of things that calls HDLError in https://github.com/DavidSouther/computron5k/blob/8adbbd3d23c1a1bc746946891bd6d489da08594a/nand2tetris/org/nand2tetris/hack/simulators/gates/HDLTokenizer.java#L250
